FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

#
# Common
#
RUN apt update -y
RUN apt install -y curl unzip software-properties-common acl

#
# ppa-ondrej-php
#
RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
RUN apt update -y

#
# PHP 8.2
#
RUN apt install -y \
    php8.2-bcmath \
    php8.2-cli \
    php8.2-fpm \
    php8.2-gd \
    php8.2-intl \
    php8.2-xdebug \
    php8.2-xml \
    php8.2-mbstring \
    php8.2-redis \
    php8.2-mysql \
    php8.2-curl \
    php8.2-xml \
    php8.2-zip


RUN for sapi in cli fpm; \
do \
    if [ -d /etc/php/8.2/$sapi ]; \
    then \
        echo "memory_limit = 1G\nerror_reporting = E_ALL\ndate.timezone = UTC\n" | tee --append /etc/php/8.2/$sapi/php.ini; \
    fi; \
done

RUN echo "\nopcache.enable=1\nopcache.enable_cli=1" | tee --append /etc/php/8.2/mods-available/opcache.ini > /dev/null
RUN echo "\nxdebug.var_display_max_data = -1\nxdebug.var_display_max_children = -1\nxdebug.var_display_max_depth = -1\nxdebug.mode = debug\nxdebug.discover_client_host = true\nxdebug.client_port = 9001" | tee --append /etc/php/8.2/mods-available/xdebug.ini > /dev/null

RUN sed -i \
        -e 's/;daemonize = yes/daemonize = no/g' \
        -e 's/pid = \/run\/php\/php8.2-fpm.pid/pid = \/run\/php8.2-fpm.pid/g' \
        /etc/php/8.2/fpm/php-fpm.conf

RUN sed -i \
        -e 's/listen = \/run\/php\/php8.2-fpm.sock/listen = 9000/g' \
        /etc/php/8.2/fpm/pool.d/www.conf

#
# Composer
#
RUN curl -LsS  https://getcomposer.org/composer.phar -o /usr/local/bin/composer
RUN chmod a+x /usr/local/bin/composer

EXPOSE 9000
ENTRYPOINT ["php-fpm8.2", "--force-stderr", "--fpm-config", "/etc/php/8.2/fpm/php-fpm.conf"]