version: "3"

services:
  php-notifications:
    build:
      context: ./php
      dockerfile: Dockerfile.${OS}
    volumes:
      - ${APP_NOTIFICATIONS_DIR}:/app
      - ./php/cache:/root/.composer/cache
    working_dir: /app

  php-users:
    build:
      context: ./php
      dockerfile: Dockerfile.${OS}
    volumes:
      - ${APP_USERS_DIR}:/app
      - ./php/cache:/root/.composer/cache
    working_dir: /app

  web-notifications:
    build:
      context: ./web-notifications
      dockerfile: Dockerfile.${WEB_SERVER}
      args:
        - PUBLIC_DIR
    volumes:
      - ${APP_NOTIFICATIONS_DIR}:/app
    working_dir: /app
    ports:
      - "8000:80"
      - "4430:443"

  web-users:
    build:
      context: ./web-users
      dockerfile: Dockerfile.${WEB_SERVER}
      args:
        - PUBLIC_DIR
    volumes:
      - ${APP_USERS_DIR}:/app
    working_dir: /app
    ports:
      - "8001:80"
      - "4431:443"

  db:
    image: mariadb:10.5
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: master

  redis:
    image: redis:7
    ports:
      - "63790:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "10250:1025"
      - "8020:8025"